### ISSUE TITLE
Latest 7.x versions has bugs

### ISSUE THREAD

**Issue by lorvent** [yajra/laravel-datatables#1302]
Hello,
either its just me or for everyone...

latest versions not working.

proper working version for me: 7.8.1

7.9.1 : datatable loading properly but search failing

7.9.3 - 7.9.6 : search not working, removeColumn not working.

is it just me or other people also having this issue?

**Comment by yajra** [comment]
@lorvent can you please paste some snippets how to reproduce the issue? Are you using collection? Anyways, I think a recent PR may have cause an issue and I made a patch for a possible fix. Can you please check again.

**Comment by lorvent** [comment]
Hello Yajra, thanks for quick response

1. yes, using collections

2. it fixes 
* removeColumn
* escapeColumns

**but search problem still exists**

when i enter first character in search box...it shows no results even though results should be shown.

controller snippet

````

$staffs = $this->userRepository->getAllNew()
            ->get()
            ->filter(function ($user) {
                return ($user->inRole('staff') && $user->id!=$this->user->id);
            })->map(function ($user) {
                return [
                    'id' => $user->id,
                    'full_name' => $user->full_name,
                    'email' => $user->email,
                    'created_at' => $user->created_at->format($this->date_format),
                ];
            });

        return $datatables->collection($staffs)
            ->addColumn('actions', 'some buttons')
            ->removeColumn('id')
            ->escapeColumns( [ 'actions' ] )->make();

````

**Comment by lk77** [comment]
escape column not working as well , 
see https://github.com/yajra/laravel-datatables/pull/1306 for the fix.

**Comment by yajra** [comment]
Maybe this is because you are using `->make()` which in return uses the index on the column instead of the name. Can you also please paste your js scripts?

Will also check @lk77 PR later when I got the chance.

**Comment by yajra** [comment]
In addition, since you are using `make()` (array response) you also need to use the index for rawColumns.

```php
->escapeColumns( [ 5 ] )
->make()
```

See http://dt54.yajrabox.com/eloquent/array for ref.

**Comment by yajra** [comment]
Found another issue on config override related to xss and was fixed v7.9.8. Can you please verify if it fixes the issue? Thanks and sorry for the inconvenience.

**Comment by lorvent** [comment]
Hello,

i just tried with 7.9.9 and search problem still exists.

7.8.1 search works properly so comparing codebase with regards to 7.8.1 may give you clue.

thanks.

**Comment by lorvent** [comment]
Hello,
Just bumping the thread.

`escapeColumns` not working well in 8.x too

if i have 2 columns and
if i apply `escapeColumns` for first one, its applying to second one and vice versa.
if i apply for both, its not working at all.

PS. `rawColumns` seems to be working well.

**Comment by lk77** [comment]
Hello,
for me it's working on 8.0.3,
ex:
```
->escapeColumns(['date', 'time'])
```
