### ISSUE TITLE
Searching rows globally with database prefix generates does not prefix primary table

### ISSUE THREAD

**Issue by paulMDA** [yajra/laravel-datatables#162]
When using a database prefix in Laravel 5.1.12 and Laravel Datatables 5.11.4, searching globally causes invalid SQL to be generated. The primary table is not prefixed with the database prefix in the generated SQL:

```php
$devices = DB::table('devices as d')
    ->leftJoin('users as au', 'd.assigned_user_id', '=', 'au.id')
    ->leftJoin('users as cu', 'd.completed_by_user_id', '=', 'cu.id')
    ->select('d.id','au.name as assigned_user_name','cu.name as completed_by_user_name');

return Datatables::of($devices)
    ->escapeColumns()
    ->make(true);
```

Searching for "b" results in:

```sql
select count(*) as aggregate from (select '1' as row_count from [prefix_devices] as [prefix_d] left join [prefix_users] as [prefix_au] on [prefix_d].[refresh_assigned_user_id] = [prefix_au].[id] left join [prefix_users] as [prefix_cu] on [prefix_d].[refresh_completed_by_user_id] = [prefix_cu].[id] where (LOWER([prefix_au].[name]) LIKE %b% or LOWER([d].[id]) LIKE %b% or LOWER([prefix_cu].[name]) LIKE %b%)) count_row_table
```

**Comment by yajra** [comment]
Thanks for reporting. Should be fixed on v5.11.5. Kindly check and confirm too. Thanks!

**Comment by paulMDA** [comment]
Thanks for your responsiveness. This issue remains in 5.11.6. Reviewing my report, I realize now that it was worded incorrectly.

In the sample above, LOWER([d].[id]) LIKE %b% is generated using the database table alias ([d]), however an alias cannot be used here. Expected behavior would LOWER([prefix_devices].[id]) ...

**Comment by BenWoodford** [comment]
Having the same (or similar?) issue on on 5.11.9, the table names in a join query where clause when searching are double-prefixed. LOWER(`prefix_prefix_table`.`id`). They're not prefixed anywhere else
