### ISSUE TITLE
Count query slow performance.

### ISSUE THREAD

**Issue by amarkotha366** [yajra/laravel-datatables#1928]
### Summary of problem or feature request

My user model have a has one relation with profile table.now when I am trying to search anything that time search not working only processing showing forever.like if I write a single letter then search work but if I write more then one letter in search box then processing forever. But if I remove relational column(profile.area') then search working.I am working over 70000 row.
![datatable](https://user-images.githubusercontent.com/6459145/49235135-9378cb80-f423-11e8-9cb3-324009290c73.PNG)

### Code snippet of problem
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{route('route)}}',
                'aaSorting' : [[0,'asc']],
                columns: [
                    {data: 'id',name: 'users.id'},
                    {data: 'name',name: 'users.name'},
                    {data: 'mobile_number',name: 'users.mobile_number'},
                    {data: 'profile.area',name: 'profile.area'},
                    {data: 'is_active',name: 'users.is_active',searchable: false},
                    {data: 'is_allowed',name: 'users.is_allowed',searchable: false},
                    {data: 'action',searchable: false}
                ]
            });

        $users = User::with('profile')->select('users.*');
          return DataTables::eloquent($users)
              ->addColumn('action', function ($user) {
                  return '<a href="#edit-'.$user->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
              })
              ->editColumn('is_active', function($status){
                  switch($status->is_active)
                  {
                    //0= Inactive, 1 = Active
                      case '0': return '<span class="label label-danger">Inactive</span>'; break;
                      case '1': return '<span class="label label-success">Active'; break;
                      default: return '<span class="label label-warning">Undefine</span>';
                  }
              })
              ->editColumn('is_allowed', function($status){
                  switch($status->is_allowed)
                  {
                      //0= Inactive, 1 = Active
                      case '0': return '<span class="label label-danger">Not Allowed</span>'; break;
                      case '1': return '<span class="label label-success">Allowed</span>'; break;
                      default: return '<span class="label label-warning">Undefine</span>';
                  }
              })
              ->rawColumns(['is_active', 'action','is_allowed'])
              ->blacklist(['created_at', 'updated_at','deleted_at','action','is_allowed','is_active'])
              ->toJson();

### **My Thinking**
If I am changing bellow this two method then it works fine and super fast.
```
    public function count()
    {
        return $this->prepareCountQuery()->count();
    }

    protected function prepareCountQuery()
    {
        $builder = clone $this->query;
        return $builder;
    }
```

### System details

- Windows 10. Local server used Laragon 4.0
- PHP Version 7.3
- Laravel Version 5.7
- Laravel-Datatables Version 8.x

**Comment by amarkotha366** [comment]
Its taking a lot of time to count total filtered row using eager loading.I have more then 50000 row.

**Comment by yajra** [comment]
Some queries are indeed slow when counting. To lessen the counting query, try chaining 

`->->skipTotalRecords()`.

**Comment by nuernbergerA** [comment]
@yajra This problem still exists!

The problem isn't the MySQL count itself it's your unnecessary wrap.

Executes the `count()` directly on the builder and is fast.
```php
return $this->prepareCountQuery()->count();
```

What you are doing is wrapping it all and count on it
```php
$builder = $this->prepareCountQuery();
        $table   = $this->connection->raw('(' . $builder->toSql() . ') count_row_table');

        return $this->connection->table($table)
            ->setBindings($builder->getBindings())
            ->count();
```

For simple queries, there might be no performance issues but for larger ones, there is a huge difference.

I don't see any reason for wrapping the query as you do, maybe the laravel builder handled the count differently.

**Comment by yajra** [comment]
@nuernbergerA thanks for the inputs. The wrapping is there since the original repo https://github.com/bgultekin/laravel4-datatables-package/blob/master/src/Bllim/Datatables/Datatables.php#L986 and I think it was added to accommodate complex queries which can't be handled by the builder.

Anyways, can you please submit a PR on your proposed solution? Thanks!

**Comment by nuernbergerA** [comment]
Sure.

**Comment by kcrob2** [comment]
Hi guys,

My code broke after this PR. I use filter to override the global search. 

Next I use the orHavingRaw function from Laravel on the query that gives me the possibility to use MySql aliases. This is my code:

`$datatableObject = DataTables::eloquent($items)
                        ->filter(function ($query) use ($module) {
                $query->orHavingRaw("id LIKE ?", ["%" . request('search.value') . "%"]);

                foreach ($module->attributeColumns as $attribute) {
                    $query->orHavingRaw("{$attribute->key} LIKE ?", ["%" . request('search.value') . "%"]);
                }
            });
`

I've tried searching through the code of the package for solutions, but haven't find anything. 
Do you guys know a solution?

Thanks in advance!

**Comment by sebastienheyd** [comment]
Hi,

I have the same problem, I think the wrapping was there to avoid error when using an sql query with an alias.

A very simple example :

```php
$query = DB::table('posts')->select(Db:raw("status AS state"))->having('state', 'publish');
Datatables::of($query);
```

After the PR : when calling `count()`,  `status AS state` will be replaced by a simple `count(*)` and then the `having` condition will fail because it doesn't know the `state` alias.

**Comment by sebastienheyd** [comment]
Have a look to my PR.

The solution I propose is to check if the current query have a `having` condition, if not the method will return the "simple" count.

I don't see any other case at the moment, maybe this is the only specific case that is problematic?

**Comment by yajra** [comment]
@sebastienheyd @kcrob2 thanks for the feedbacks. I released the `having` patch on v9.17.3. Please check again and verify if it fixes the issue. If not, I will have to revert all the changes on count until we find a better solution. 🍻

**Comment by kcrob2** [comment]
@yajra @sebastienheyd Thanks for the fast reply! I still get the following error: 1054 Unknown column 'column' in 'having clause'. 

The following if statement still returns true if the 'having' queries are in the filter function.
`if (empty($builder->havings)) {
            return $builder->count();
        }`

I think the filter function get's called somewhere after the count or somehow, but can't exactly figure out where it goes wrong.

**Comment by sebastienheyd** [comment]
Mmm, can you try this :

```php
public function count()
{
    $builder = $this->prepareCountQuery();
    $query = $builder->toSql();

    if (!preg_match('#\shaving\s#', $query)) {
        return $builder->count();
    }

    $table = $this->connection->raw('('.$query.') count_row_table');

    return $this->connection->table($table)
        ->setBindings($builder->getBindings())
        ->count();
}
```

Or eventually post the result of `$builder->toSql()` ?

I have a doubt, maybe `$builder->havings` can be empty when using sub conditions.

**Comment by kcrob2** [comment]
@sebastienheyd @yajra 

Yes, it works now when I use it with a search request!

When I leave it empty it only shows the maximum results chosen in datatables, this case 10. I have the following query when I leave the search field empty:

"select `module_telers`.`id`, `module_telers`.`publiceren`, `module_telers`.`archief`, `module_telers`.`uitgelicht`, `module_telers`.`image_header`, `module_telers`.`bedrijfsnaam`, `module_telers`.`titel`, `module_telers`.`plaats`, group_concat(DISTINCT productenAlias.titel SEPARATOR ', ') as producten from `module_telers` left join `relation_producten_telers` on `module_telers`.`id` = `relation_producten_telers`.`telers_id` left join `module_producten` as `productenAlias` on `productenAlias`.`id` = `relation_producten_telers`.`producten_id` group by `module_telers`.`id`"

If statement works now, but something still goes wrong when the 
`return $this->prepareCountQuery()->count();` get's called

**Comment by sebastienheyd** [comment]
Can you try without `group_concat(DISTINCT productenAlias.titel SEPARATOR ', ') as producten` ?

I think if `having` is a problem, `as` is certainly a problem too.

**Comment by sebastienheyd** [comment]
Or try this :

```php
public function count()
{
    $builder = $this->prepareCountQuery();
    $query = $builder->toSql();

    if (!preg_match('#\shaving\s|^select.*\sas\s.*from#i', $query)) {
        return $builder->count();
    }

    $table = $this->connection->raw('('.$query.') count_row_table');

    return $this->connection->table($table)
        ->setBindings($builder->getBindings())
        ->count();
}
```

**Comment by yajra** [comment]
@nuernbergerA @sebastienheyd will revert all the changes on count as it breaks several apps. New issue reported https://github.com/yajra/laravel-datatables/issues/2613.

**Comment by yajra** [comment]
To add, maybe we can use `$this->isComplexQuery($builder)` to use for simple count. But I can't test and would need help to verify if it works.

```php
public function count()
{
    $builder = $this->prepareCountQuery();
    $query = $builder->toSql();

    if (!$this->isComplexQuery($builder)) {
        return $builder->count();
    }

    $table = $this->connection->raw('('.$query.') count_row_table');

    return $this->connection->table($table)
        ->setBindings($builder->getBindings())
        ->count();
}
```

**Comment by yajra** [comment]
Count changes reverted v9.17.4. Please feel free to submit another PR for possible performance improvements. Thanks!

**Comment by nuernbergerA** [comment]
I will PR a new solution with tests.

Can someone tell me what queries are causing issues with a normal `count()`? So I have more data to test.

**Comment by nuernbergerA** [comment]
Hey @sebastienheyd and @kcrob2 

can you confirm that the new solution works?
#2616

**Comment by kcrob2** [comment]
@sebastienheyd @nuernbergerA @yajra 

Yes!!!! Can confirm this function works!! Thanks for the help @sebastienheyd @yajra !!!

`public function count()
{
    $builder = $this->prepareCountQuery();
    $query = $builder->toSql();

    if (!$this->isComplexQuery($builder)) {
        return $builder->count();
    }

    $table = $this->connection->raw('('.$query.') count_row_table');

    return $this->connection->table($table)
        ->setBindings($builder->getBindings())
        ->count();
}`

**Comment by sebastienheyd** [comment]
@nuernbergerA adding tests is what we should have done from the beginning ! Your solution works and is better than my simple quickfix, well done !

**Comment by kcrob2** [comment]
@nuernbergerA  yes tested your PR and works with me also! Thnx!!
