### ISSUE TITLE
Laravel 5.2 Support

### ISSUE THREAD

**Issue by kayyyy** [yajra/laravel-datatables#313]
Hello,

first: awesome packages and really thanks for this awesome open source package.

Can you tell me when your package will support Laravel 5.2?

If i install your current 6er version and add the service provider, i get the error
```
Call to undefined method Illuminate\Foundation\Application::bindShared()
```

**Comment by yajra** [comment]
@kayyyy v6.0.0 of datatables should work on Laravel 5.2. However, I think Laravel Collective form is not yet supporting 5.2 which causes the bindShared issue.

**Comment by yajra** [comment]
If you want to work with L5.2 now, you can use my `html` fork for it to work. Just add this on your composer.json. 

```json
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/yajra/html.git"
    }
  ],
```

**Comment by yajra** [comment]
LaravelCollective HTML support for v5.2 was just released and should fix this issue. Kindly try again. Thanks!

**Comment by lhdev** [comment]
Please update your package to use the new laravelcollective package.
Your composer still shows: "laravelcollective/html": "~5.0", but laravelcollective html is actually 5.2 now.

**Comment by yajra** [comment]
I think ~5.0 should work for 5.2. Anyways, I think you can just specify the version you need on your composer. I will not be be able to update the package for a week or so. Sorry!

Sent from Outlook using iPhone




On Wed, Dec 23, 2015 at 8:59 PM -0800, "Troy Siedsma" <notifications@github.com> wrote:












Please update your package to use the new laravelcollective package.

Your composer still shows: "laravelcollective/html": "~5.0", but laravelcollective html is actually 5.2 now.

**Comment by kayyyy** [comment]
Thank you, i will give it a try! :+1: 

And merry christmas

**Comment by yajra** [comment]
Laravel 5.2 installation should work now since `html` package now supports 5.2. Thanks!
